name: educheck
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core Firebase (Compatible versions)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # Google Sign-In
  google_sign_in: ^6.3.0
  
  # Storage
  flutter_secure_storage: ^9.2.4
  
  # HTTP
  http: ^1.2.2
  
  # Image/File Picking
  image_picker: ^1.2.0
  file_picker: ^8.3.7
  camera: ^0.10.6
  permission_handler: ^11.4.0
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # UI
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.9
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  
  # Utils
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true